thedaviddias/Front-End-Performance-Checklist

README.md

- Where is commits' message styles?
Fix link tag
- Unindent list tag

Fix link list

---

.github/CONTRIBUTING.md

I think there is a minor error on contribution template; I changed the open issues link with anchor tag.
**Fixes**: #
-
-
-
👍 Thank you!

update open issues link in contribution md

---

README.md

Addition of Pingdom speed test tool
- Addition of Pingdom Website Speed Testing tool - https://tools.pingdom.com/ - in the Performance Tools section

Add Pingdom to performance tools list

---

README.md

Adding new tools for image optimization and analysis
New tools that have been added -
- Kraken.io (online image optimization)
- Compressor.io (online image optimization)
- Cloudinary (optimization analysis)
- lazysizes (Lazy loading library)

Add new image optimization and analysis tooling

---

README.md

Add IcoMoon app
adding IcoMoon link to font tooling section (Mainly used for creating custom builds of icon fonts)

Add IcoMoon to font tooling

---

README.md

Adding Global Latency Testing tool
Adding Global Latency Testing tool by apex.sh to TTFB tooling section 
Sample Test Results -
- https://latency.apex.sh/?url=https://www.google.com
- https://latency.apex.sh/?url=https://www.google.com&compare=https://www.google.co.in

Add Latency to TTFB tooling

---

README.md

FOIT issue added to checklist under Fonts section
Flash of Invisible Text section added with resources about `font-display` property

Adding FOIT issue under Fonts section

---

README.md

Addition of Uptime monitoring tools
Adding the following Uptime Monitoring Tools -
-  Pingdom
- Uptime Robot
These tools have been added to the General Performance Tools section

Adding Uptime monitoring tools

---

README.md

Typos and grammar
Spelling -
- `ressource` 🡺 `resource`
- `Regroupe` 🡺 `Regroup`
Grammar - 
- `embed` 🡺 `embedded`

Fix typos & grammar

---

README.md

Adding resources for Brotli compression
Added Brotli compression side by side with GZIP compression
Also included a tool for testing whether a website is using Brotli compression
Also fixed a typo with emoji icon used for GZIP compression tool (replaced 📖 with 🛠)

Adding information about Brotli compression

---

README.md

Typos in Emoji and tool link
Replace 📖 with 📹 for Youtube link
Replace 📖 with 🛠 for loadCSS library
Replace 📖 with 🛠 for webpack-bundle-analyzer
Fix the link for Google's 3G Mobile Speed Test - https://testmysite.thinkwithgoogle.com/intl/en-us (The previously used URL was redirecting to the above URL)

Fix Emoji typos and tool link

---

README.md

Changed the example for "CSS Concaternation". Now using CSS instead of JS.
The section talks about CSS files, but shows an example of JS files. I changed the example to a CSS example.
👍 Thank you!

Changed css example "concatenation"

---

README.md

Adding online minification tool and fixing a typo with emoji icon used
The [Refresh-SF](http://refresh-sf.com) tool can be used to minify HTML, CSS, and JS. Therefore I have added it in the 3 sections (HTML/CSS/JS minification) separately
This tool is open source. The source for the same is available at - https://github.com/gpbmike/refresh-sf/
Also, I have replaced the icon 📖 with 🛠 for `uglify-js - npm`

Adding Refresh-SF tool in HTML/CSS/JS section

---

README.md

Add Dotcom-Tools under general Performance tools section

Add Dotcom-Tools under general Performance tools section

---

README.md

Adds PWMetrics - CLI tool and lib to gather performance metrics.

Add PWMetrics

---

README.md

Missing Russian translation
- Add Russian translation link in the README

Add 🇷🇺 Russian translation

---

README.md

Missing french translation
- Add french translation link in the README

Add 🇫🇷 French translation

---

README.md

**Proposed changes:**
- Replace Javascript with JavaScript

Replace Javascript with JavaScript

---

README.md

Fix link in ToC

---

README.md

Make a little mistake, I'm sorry :smiley: 
- Fix title for translation link

Fix title for translation link

---

README.md

Just a tiny improvement
- Replace Github with GitHub

Replace Github with GitHub

---

README.md

Because the quote does not support the list, and it does not appear as it should.
- Add new lines to items in quotes

Add new lines to items in quotes

---

README.md

Link to resource about keeping above the fold content size below 14.6KB (compressed)
Closes #26

Add resource under Critical CSS section

---

README.md

**Fixes**: LazyLoad only for offscreen images, as in issue #31

Lazy load only offscreen

---

README.md

**Fixes**: Also fixes what I wrote in the second comment of #31 about lazyloading alternative images at mouseover.

Added a list point about alternative images

---

README.md

**Fixes**: #
-
-
-
👍 Thank you!

fix(typo): connexion => network connection

---

README.md

- Add link to text version of The Cost Of JavaScript

Add link to text version of The Cost Of JavaScript

---

README.md

An optimization tool for SVG files was not available under Images optimization checklist, therefore I have added one.
[SVGOMG](https://jakearchibald.github.io/svgomg/) can be used to optimize SVG files.

Add SVG optimization link

---

README.md

- relative path to License file
👍 Thank you!

FIX - path to License

---

README.md

Add https://treo.sh to the list of performance tools.
👍 Thank you, this checklist is terrific!

Add treo.sh

---

README.md

**Fixes**: N/A
Simple wording fix for the iframes section.
The iframes sentece made no sense.

Update wording for iframes section

---

README.md

- Added Lighthouse to the Performance tools list
👍 Thank you!

Updated Performance tools

---

README.md

APC - the most comprehensive guide for optimising performance of Angular applications (don't be confused with AngularJS)
**Fixes**: #
-
-
-
👍 Thank you!

Adding angular performance checklist

---

README.md

Added https://yellowlab.tools/ to Performance Tools
**Fixes**: Added new reference
Added another useful online tool to test/analyse website performance 
-
-
-
👍 Thank you!

Added Yellowlabs

---

README.md

*DISCLAIMER*
I am the maintainer of Project Wallace, so I am biased.
I think Project Wallace is filling a gap that other projects leave behind: tracking progress of the css stats over time. Therefore I think this is a valuable addition to this wonderful checklist. Example of [GitHub on Project Wallace](https://www.projectwallace.com/teamwallace/github)

Adds Project Wallace to CSS analysis tools

---

README.md

📖  🡆 🛠 (CSS Stats tool labelled as an article )
📖  🡆 📹 (Youtube video labelled as an article)

Emoji Typos

---

README.md

I see your article does not have the Vietnamese version. I would like to contribute my translation
**Fixes**: #
-
-
-
👍 Thank you!

Update Vietnamese version

---

README.md

[Speedrank](https://speedrank.app) monitors the performance of your website in the background. It displays Lighthouse reports in time and delivers recommendations for improvement. Speedrank is a paid product with 14-day-trial.
- Add Speedrank to the list of performance testing tools.
👍 Thank you!

Add Speedrank

---

README.md

Add packtracker.io to Tools section

---

README.md

**Fixes**: #
- [ X] Check the commit's or even all commits' message styles matches our requested structure.
- [X ] Check your code additions will fail neither code linting checks nor unit test.
My team wrote a tool that utilizes Google lighthouse to compare how optimized a current sites images are vs how much images can be optimized using a tool like ImageEngine.  
Add reference to demo tool on Readme
-
-
-
👍 Thank you!

Add reference to ImageEngine Demo test

---

README.md

**Fixes**: #68 
Just a small introduction to implement resource prefetching with prefetch, dns-prefetch and prerender directives. The description can be improved in the future.
This is a resolution of the issue #68.
- Add new sub-section in HTML section 
👍 Thank you! Zoubi David ;)

Add section for pre-load ressources

---

README.md

Hi,
I always use the checklist to find forgotten/lost stuff. Thank you for making it 👍  
I wanted to share the tool we recently released [Exthouse](https://github.com/treosh/exthouse). It automatically audits the performance impact of a browser extension on user experience and provides a detailed report powered by Lighthouse.
Here's report example:
P.S. It's placed as first in a tooling section, is it ok? :)

Add Exthouse tool

---

README.md

Add link to js-dependency-viewer tool

---

README.md

HTML minification will take care of comments removal and dropping unnecessary attributes. So calling those out separately seems like a distraction. 
(Similarly we wouldn't recommend using short javascript variable names or removing comments from JS.)

nix html comments & attributes removal

---

README.md

Add Polish link

---

README.md

As this is a simple self-explaining **"adding my library" docs change**, I haven't opened a separate issue for it.

docs(lazyloading): added polyfill to that section

---

README.md

**Fixes**: #
Updating an outdated link under "references". Fixes issue: https://github.com/thedaviddias/Front-End-Performance-Checklist/issues/133
- Front-End Performance Checklist 2018  updated to the 2021 link. 
- Added (in the brackets) its also in MS word doc format.
- Updated link title with new year
👍 Thank you!

Updated "References" link

---

README.md

Hey there, added LogRocket to the list of tools. Figured recent additions go last.
**Fixes**: #
- [ x] Check the commit's or even all commits' message styles matches our requested structure.
- [x ] Check your code additions will fail neither code linting checks nor unit test.
Expands list of solutions
- Adding LogRocket to list of tools
-
-
👍 Thank you!

Adding LogRocket to list of solutions

---

README.md

I added CSS minifier that works best and better than CSSnano
**Fixes**: #
I checked the CSS nano minfier is not working well in opera mini that's why I added alternative 
- Help developer
- Clean tool UI
- one click copy clear and minify button
👍 Thank you!

Added CSS minifier

---

README.md

resolve #136 
Missing Persian translation
add 🇮🇷 Persian translation
Thank you

add 🇮🇷 Persian translation

---

README.md

fix vietnamese flag icon

---

README.md

Added Italian translation link in Translation section.

Update README.md | Resolve #153 (Italian translation)

---

README.md

This PR adds a link to a comprehensive page teaching more about Brotli that I thought could be a nice fit for people not aware of what Brotli actually is.
* Adds a link to learn more about Brotli.
👍 Thank you!

chore: add link to learn more about Brotli
